
// <copyright file="PostLinkIncidentToEmailSenderAction.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/22/2023 4:04:14 PM</date>
// <summary>Implements the PostLinkIncidentToEmailSenderAction Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>



namespace NEACCOMPAGNEMENTCRM.NEACCOMPAGNEMENTCRM.Plugins
{
    using System;
    using System.Linq;
    using System.ServiceModel;
    using global::NEACCOMPAGNEMENTCRM.Common;
    using Microsoft.Xrm.Sdk;
    /// <summary>
    /// PostLinkIncidentToEmailSenderAction Plugin.
    /// </summary>    
    public class PostLinkIncidentToEmailSenderAction: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostLinkIncidentToEmailSenderAction"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostLinkIncidentToEmailSenderAction(string unsecure, string secure)
            : base(typeof(PostLinkIncidentToEmailSenderAction))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }
            try
            {
                IPluginExecutionContext context = localContext.PluginExecutionContext;
                IOrganizationService service = localContext.OrganizationService;
                EntityReference targetEntityRef = context.InputParameters["Target"] as EntityReference;
                if (targetEntityRef != null && targetEntityRef.LogicalName == Email.EntityLogicalName)
                {
                    localContext.Trace("0. Start PostLinkIncidentToEmailSenderAction plugin.");

                    EmailService.LinkIncidentToEmailSender(service, targetEntityRef);

                    localContext.Trace("1. End PostLinkIncidentToEmailSenderAction plugin.");
                }
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
