
// <copyright file="PostLinkIncidentToEmailSenderAction.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/22/2023 2:35:55 PM</date>
// <summary>Implements the PostLinkIncidentToEmailSenderAction Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace NEACCOMPAGNEMENTCRM.NEACCOMPAGNEMENTCRM.Plugins
{

    /// <summary>
    /// PostLinkIncidentToEmailSenderAction Plugin.
    /// </summary>    
    public class PostLinkIncidentToEmailSenderAction: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostLinkIncidentToEmailSenderAction"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostLinkIncidentToEmailSenderAction(string unsecure, string secure)
            : base(typeof(PostLinkIncidentToEmailSenderAction))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "depne_LinkIncidentToEmailSender", "email", new Action<LocalPluginContext>(ExecutePostLinkIncidentToEmailSenderAction)));
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostLinkIncidentToEmailSenderAction(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            throw new InvalidPluginExecutionException("khg");
            // TODO: Implement your custom Plug-in business logic.
        }
    }
}
